// react-app-webpack/src/components/UsersList.jsx
import React, { Component } from 'react';
import NavBar from './NavBar'
import { Link } from 'react-router-dom';

class UsersList extends Component {
  constructor (props, context) {
    super(props, context)

    this.state = {
      users: [],
      fetching: false
    }
  }

  render() {
    const {fetching, users} = this.state

    return (
      <div>
        <NavBar />
        {fetching ? (
          <div>
            FETCHING...
          </div>
        ) : (
          <div>{users.map(user => {
            return (
              <Link key={user.id}
                    to={`/users/${user.id}`}
                    className="flex-row">
                <div>{user.id}</div>
                <div>{user.name}</div>
                <div>{user.email}</div>
              </Link>
            )
          })}
          </div>
        )}
      </div>
    );
  }

  loadUsers () {
    this.setState({fetching: true})
    fetch('http://jsonplaceholder.typicode.com/users')
      .then(res => res.json()).then(users => {
      this.setState({fetching: false, users})
    })
  }

  componentDidMount () {
    this.loadUsers()
  }
}

export default UsersList;

// vue-app-webpack/src/components/UsersList.vue
<template>
  <div>
    <nav-bar/>
    <div v-if="fetching">
      FETCHING...
    </div>
    <div v-else="">
      <router-link v-for="user in users"
           :key="user.id"
           :to="`/users/${user.id}`"
           class="flex-row">
        <div>{{user.id}}</div>
        <div>{{user.name}}</div>
        <div>{{user.email}}</div>
      </router-link>
    </div>
  </div>
</template>

<script>
import NavBar from './NavBar'

export default {
  name: 'UsersList',
  components: {
    NavBar
  },
  data () {
    return {
      users: [],
      fetching: false
    }
  },
  methods: {
    loadUsers () {
      this.fetching = true
      fetch('http://jsonplaceholder.typicode.com/users')
        .then(res => res.json()).then(users => {
          this.users = users
          this.fetching = false
        })
    }
  },
  mounted () {
    this.loadUsers()
  }
}
</script>

<style scoped>
  .flex-row {
    display: flex;
    flex-direction: row;
    justify-content: space-around;
  }
</style>
