// react-app/src/components/UsersList.jsx
import React, { Component } from 'react';
import NavBar from './NavBar'

class UsersList extends Component {
  constructor (props, context) {
    super(props, context)

    this.state = {
      users: [],
      fetching: false
    }
  }

  render() {
    const {fetching, users} = this.state

    return (
      <div>
        <NavBar />
        {fetching ? (
          <div>
            FETCHING...
          </div>
        ) : (
          <div>{users.map(user => {
            return (
              <div key={user.id} className="flex-row">
                <div>{user.id}</div>
                <div>{user.name}</div>
                <div>{user.email}</div>
              </div>
            )
          })}
          </div>
        )}
      </div>
    );
  }

  loadUsers () {
    this.setState({fetching: true})
    fetch('http://jsonplaceholder.typicode.com/users')
      .then(res => res.json()).then(users => {
      this.setState({fetching: false, users})
    })
  }

  componentDidMount () {
    this.loadUsers()
  }
}

export default UsersList;

// angular-app-webpack/src/app/users-list/users-list.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from '../user'

@Component({
  selector: 'app-users-list',
  templateUrl: './users-list.component.html',
  styleUrls: ['./users-list.component.css']
})
export class UsersListComponent implements OnInit {
  fetching: Boolean = false;
  users: User[];

  constructor() { }

  loadUsers () {
    this.fetching = true;
    fetch('http://jsonplaceholder.typicode.com/users')
      .then(res => res.json()).then(users => {
      this.users = users;
      this.fetching = false;
    })
  }

  ngOnInit() {
    this.loadUsers();
  }

}

<div>
  <app-navbar></app-navbar>
  <div *ngIf="fetching">
    FETCHING...
  </div>
  <div #elseBlock>
    <a *ngFor="let user of users"
       routerLink="/users/{{user.id}}"
       class="flex-row">
      <div>{{user.id}}</div>
      <div>{{user.name}}</div>
      <div>{{user.email}}</div>
    </a>
  </div>
</div>
