// vue-app-webpack/src/components/UserDetail.vue
<template>
  <div>
    <nav-bar/>
    <div v-if="fetching">
      FETCHING...
    </div>
    <div v-else-if="user">
      <h1>Detail information:</h1>
      <div>
        <div>{{user.id}}</div>
        <div>{{user.name}}</div>
        <div>{{user.email}}</div>
      </div>
    </div>
  </div>
</template>

<script>
import NavBar from './NavBar'

export default {
  name: 'UserDetail',
  components: {
    NavBar
  },
  data () {
    return {
      user: null,
      fetching: false
    }
  },
  methods: {
    loadUser (id) {
      this.fetching = true
      fetch(`http://jsonplaceholder.typicode.com/users/${id}`)
        .then(res => res.json()).then(user => {
          this.user = user
          this.fetching = false
        }).catch(err => {
          console.log(err)
          this.fetching = false
        })
    }
  },
  mounted () {
    this.loadUser(this.$route.params.userId)
  }
}
</script>

<style scoped>
</style>

// react-app-webpack/src/components/UserDetail.jsx
import React, { Component } from 'react';
import NavBar from './NavBar'

class UserDetail extends Component {
  constructor (props, context) {
    super(props, context)

    this.state = {
      user: null,
      fetching: false
    }
  }

  render() {
    const {fetching, user} = this.state

    return (
      <div>
        <NavBar />
        {fetching ? (
          <div>
            FETCHING...
          </div>
        ) : (
          user ? (
            <div>
              <h1>Detail information:</h1>
              <div>
                <div>{user.id}</div>
                <div>{user.name}</div>
                <div>{user.email}</div>
              </div>
            </div>
          ) : null
        )}
      </div>
    );
  }

  loadUser (id) {
    this.setState({fetching: true})
    fetch(`http://jsonplaceholder.typicode.com/users/${id}`)
      .then(res => res.json()).then(user => {
      this.setState({fetching: false, user})
    })
  }

  componentDidMount () {
    this.loadUser(this.props.match.params.userId)
  }
}

export default UserDetail;
